baseURL = "/"
languageCode = "en-us"
title = "GrocerySpend.io"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"

[params]
  github = "https://github.com/bryanjknight/groceryspend.io"
  background_color_class = "bg-dark-gray"
  custom_css = [ "css/custom.css" ]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true