// Code generated by sqlc. DO NOT EDIT.

package users

import (
	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID `json:"id"`
	AuthProviderID string    `json:"authProviderID"`
	AuthSpecificID string    `json:"authSpecificID"`
}
