version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example    
    ports:
      - 18081:8081

  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 28081:8081