version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:   
      - ./docker_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
  
  prediction-service:
    image: groceryspend/predict:local
    restart: always
    ports:
      - 5000:5000

  #
  # Not actively using redis, but leaving for ease
  #
  # redis:
  #   image: redis
  #   restart: always
  #   ports: 
  #     - 6379:6379

  # redis-commander:
  #   image: rediscommander/redis-commander
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #     - HTTP_USER=root
  #     - HTTP_PASSWORD=qwerty
  #   ports:
  #     - 28081:8081