apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hello-world-svc
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      host: hello.groceryspend.io
      paths:
      - path: /
        backend:
          serviceName: hello-world-svc
          servicePort: 80