name: Server CICD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Build server
        working-directory: server
        run: make build

      - name: Run unit tests
        working-directory: server
        run: make unit-test
  