name: Web Portal CICD
on: 
  push:
    paths:
    - 'web-portal/**'
  pull_request:
    paths:
    - 'web-portal/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependences
        working-directory: web-portal
        run: npm install

      - name: Build web-portal
        working-directory: web-portal
        run: npm run build

      - name: Run unit tests
        working-directory: web-portal
        run: npm run test
  
      - name: Run code coverage
        working-directory: web-portal
        run: npm run test:coverage

      - name: Dockerize
        working-directory: web-portal
        run: make build
        env:
          DOCKER_TAG: ${{ github.run_number }}

      - name: Log into Docker Hub
        working-directory: web-portal
        run: echo $DOCKER_PASS | docker login --username bknight1983 --password-stdin
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_API_TOKEN }}

      - name: Push to Docker Hub
        working-directory: web-portal
        run: make push
        env:
          DOCKER_TAG: ${{ github.run_number }}
        

      # TODO: rollout on k8s