name: Web Portal CICD
on: 
  push:
    paths:
    - 'web-portal/**'
  pull_request:
    paths:
    - 'web-portal/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependences
        working-directory: web-portal
        run: npm install

      - name: Build web-portal
        working-directory: web-portal
        run: npm run build

      - name: Run unit tests
        working-directory: web-portal
        run: npm run test
  
      - name: Run code coverage
        working-directory: web-portal
        run: npm run test:coverage

      - name: Dockerize
        working-directory: web-portal
        run: docker build -t web-portal:local .

      # TODO: deploy to container registry, rollout on k8s
