name: Web CICD
on: 
  push:
    paths:
    - 'web/**'
  pull_request:
    paths:
    - 'web/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependences
        working-directory: web
        run: npm install

      - name: Build web
        working-directory: web
        run: npm run build

      - name: Run unit tests
        working-directory: web
        run: npm run test
  
      - name: Run code coverage
        working-directory: web
        run: npm run test:coverage